-- This file is intentionally left empty.
-- 
-- For development and testing, use seed scripts from:
-- supabase/seed-scripts/
--
-- Available seed scripts:
-- - seed_upcoming_matches.sql (for upcoming matches endpoint testing)
-- - seed_leaderboard_test_data.sql (for leaderboard endpoint testing)
--
-- Usage:
-- \i supabase/seed-scripts/seed_leaderboard_test_data.sql

